import React, { useState } from 'react'
import { ArrowUpRight, Check, ChevronLeft, X } from 'lucide-react'
import { timeSlots } from '../../data/catalog'

export default function BookingModal({ type, close, cart, total, setCart, onSubmitted }) {
  const [step, setStep] = useState(1)
  const [selectedSlot, setSelectedSlot] = useState(null)
  if (type === 'cart') return <div className="modal-backdrop" onClick={close}><aside className="drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={close} aria-label="Fermer"><X/></button><span className="eyebrow lavender">YOUR BAG</span><h2>Panier <small>{cart.length}</small></h2>{cart.length ? <><div className="drawer-items">{cart.map((item, index) => <div className="drawer-item" key={`${item.id}-${index}`}><img src={item.image} alt=""/><div><strong>{item.name}</strong><span>{item.price}€</span></div><button onClick={() => setCart(cart.filter((_, itemIndex) => itemIndex !== index))} aria-label={`Supprimer ${item.name}`}>×</button></div>)}</div><div className="drawer-total"><span>Sous-total</span><strong>{total}€</strong></div><button className="button full">Passer au paiement <ArrowUpRight size={16}/></button></> : <div className="empty-cart"><p>Votre panier est encore vide.</p></div>}</aside></div>
  return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Fermer"><X/></button><ModalContent type={type} step={step} setStep={setStep} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} onSubmitted={onSubmitted}/></div></div>
}

function ModalContent({ type, step, setStep, selectedSlot, setSelectedSlot, onSubmitted }) {
  const [submitted, setSubmitted] = useState(false)
  if (submitted) return <div className="success"><Check size={35}/><h2>Merci, c'est envoyé.</h2><p>Notre équipe revient vers vous sous 48h ouvrées.</p><button className="button" onClick={onSubmitted}>Fermer</button></div>
  if (type === 'booking') return <><span className="eyebrow orange">BOOKING REQUEST</span><h2>Réserver une session</h2><p className="modal-lead">Choisissez une prestation, une date et un créneau.</p><label>Votre service<select><option>Tatouage — consultation</option><option>Piercing — première pose</option><option>Retouche</option></select></label><label>Votre nom<input required placeholder="Prénom Nom"/></label><label>Email<input required type="email" placeholder="vous@email.com"/></label><div className="date-picker"><span>Disponibilités — Octobre 2024</span><div>{['12', '14', '16', '21', '23', '26'].map((day) => <button key={day}>{day}<small>OCT</small></button>)}</div></div><div className="time-slots">{timeSlots.map((slot) => <button disabled={slot.state === 'unavailable'} className={`${slot.state} ${selectedSlot === slot.time ? 'chosen' : ''}`} key={slot.time} onClick={() => setSelectedSlot(slot.time)}>{slot.time}</button>)}</div><button className="button full" disabled={!selectedSlot} onClick={() => setSubmitted(true)}>Envoyer la demande <ArrowUpRight size={16}/></button></>
  if (type === 'quote') return <><div className="stepper"><span className="active">01</span><i/><span className={step > 1 ? 'active' : ''}>02</span><i/><span className={step > 2 ? 'active' : ''}>03</span></div><span className="eyebrow orange">CUSTOM TATTOO</span><h2>{step === 1 ? 'Parlons de votre idée.' : step === 2 ? 'Quelques détails.' : 'On garde le contact.'}</h2>{step === 1 && <><p className="modal-lead">Même les idées floues sont les bienvenues.</p><label>Décrivez votre projet<textarea required placeholder="Une phrase, une inspiration, une histoire…"/></label><label>Style envisagé<select><option>Je ne sais pas encore</option><option>Fine line</option><option>Blackwork</option><option>Ornemental</option></select></label></>}{step === 2 && <><label>Emplacement<input placeholder="Avant-bras, dos, côte…"/></label><label>Taille approximative<select><option>Petit (moins de 5 cm)</option><option>Moyen (5 à 15 cm)</option><option>Grand (plus de 15 cm)</option></select></label><label>Référence visuelle<input type="file" accept="image/*"/></label></>}{step === 3 && <><label>Votre nom<input required placeholder="Prénom Nom"/></label><label>Email<input required type="email" placeholder="vous@email.com"/></label></>}<div className="modal-actions">{step > 1 && <button className="text-link" onClick={() => setStep(step - 1)}><ChevronLeft size={15}/> Retour</button>}<button className="button" onClick={() => step < 3 ? setStep(step + 1) : setSubmitted(true)}>{step < 3 ? 'Continuer' : 'Envoyer mon projet'} <ArrowUpRight size={16}/></button></div></>
  return <><span className="eyebrow lavender">YOUR EXPERIENCE</span><h2>Votre avis compte.</h2><label>Note <div className="rating-input" role="radiogroup" aria-label="Note">★★★★★</div></label><label>Votre témoignage<textarea required placeholder="Racontez-nous votre expérience…"/></label><label>Ajouter une photo<input type="file" accept="image/*"/></label><button className="button full" onClick={() => setSubmitted(true)}>Publier mon avis <ArrowUpRight size={16}/></button></>
}
